### ISSUE TITLE
final paper peer review 2

### ISSUE THREAD

**Issue by Lorina-Y** [leoyliu/Determinants-of-Wage-Variation-in-Canada#3]
**Peer Review from Lorina Yang**
I am Lorina Yang, and I’m peer-reviewing Leo Liu's paper on "Determine the wage variation in Canada"
The feedback below conducted at 14:15 on Nov 27, 2024
**Opening Statement Summary:**
The project examines how education levels impact average hourly wages for Canadians aged 25-54 from 2000 to 2019. Using a linear regression model, it explores the correlation between educational attainment and wages, supporting the hypothesis that higher education leads to increased earnings. The findings offer insights for economic and educational policy-making.

**Strong Positive Points:**
- **Clear model setup and README.:** A strong positive aspect of this project is the clear and well-structured model setup, such as employ linear regression model for interpretation of correlation, which is easy to follow and thoroughly documented. The accompanying README provides detailed instructions, making it straightforward for users to understand.

- **Clear research focus:** The project has a clear research focus, aiming  explores the correlation between educational attainment and wages, and have good reason for why conduct the research. 

-  **Clear Table of Content:** the project is the inclusion of a well-organized table of contents on the first page of the paper. This feature allows readers to easily navigate through the document, enhancing the readability. And reflects the thoughtful structuring of the paper, making it more accessible and easier to engage with for both peers and reviewers.

**Critical Improvements Needed:**
- **Explain relationship between variables:** In the data section of your paper, you need  include a Summary statistics of your variables, and explain if there are any relationships between the variables, for example, it is possible that education and age are related to each other, since elder may have high education level such as PhD than people who are 25 years old.
- **Intext citation:** In the second paragraph of subsection of model setup under the model section of your paper,  the in-text citation of rstanarm package is not valid, you need to check your citation format and fix the typo.
- **Model Justification:** The explanation for selecting and validating a simple linear regression lacks sufficient detail. You should expand this section by add visualization to show whether a linear relationship exist, and maybe consider offering a theoretical foundation for the choice of prior would enhance the model’s justification. Including real-world examples or case studies where similar models and prior have been successfully applied in investigate the relationship could further support the choice of models. 

**Suggestions for Improvement:**
- Carefully proofread the document to ensure there are no grammatical errors or typos.
- Add additional visualizations to better illustrate the key findings.
- Integrate relevant academic literature to support the discussions and emphasize the significance of the findings and methodologies.
- Present the data overview in a clear table format for improved readability and organization.
- You may consider potential relationship of age and education level as one limitation which may affect the outcome of your study

Evaluation:
o	R/Python cited ([1]/1 pts)
	[R is properly cited]
o	Data cited ([1]/1 pts)
	[Data source OpenDataToronto is properly cited]
o	Class paper ([1]/1 pts)
	[Not mention class paper]
o	LLM documentation ([1]/1 pts)
	[LLM usage is clearly indicated in readme and LLM folder]
o	Title ([1]/2 pts)
	[Title is clear and easy to read, but lack of detail]
o	Author, date, and repo ([2]/2 pts)
	[Author, date, and repo is clearly indicated]
o	Abstract ([4]/4 pts)
	[Abstract is clear and detailed]
o	Introduction ([4]/4 pts)
	[All criteria of introduction is meet]
o	Estimand ([1]/1 pts)
	[Estimand is clearly indicated and explained]
o	Data ([5]/10 pts)
	[haven’t finish yet, not explain variables]
o	Measurement ([4]/4 pts)
	[clearly defined with example]
o	Model ([5]/10 pts)
	[model set up is clear but haven’t finish yet, lack of justification]
o	Results ([0]/10 pts)
	[haven’t finish]
o	Discussion ([0]/10 pts)
	[haven’t finish]
o	Prose ([5]/6 pts)
	[good words used, and sentence are clear and precise]
o	Cross-references ([0]/1 pts)
	[mostly correct, but has typo]
o	Captions ([0]/2 pts)
	[No visualization]
o	Graphs/tables/etc ([0]/4 pts)
	[No visualization]
o	Surveys, sampling, and observational data appendix ([0]/10 pts)
	[Not done]
o	Referencing ([4]/4 pts)
	[reference are property cited and included in bib file]
o	Commits ([2]/2 pts)
	[commits message are clear]
o	Sketches ([2]/2 pts)
	[good]
o	Simulation ([3]/4 pts)
	[good]
o	Tests ([3]/4 pts)
	[can be more]
o	Parquet ([1]/1 pts)
	[noted]
o	Reproducible workflow ([4]/4 pts)
	[the workflow is mostly reproducible]
o	Enhancements ([2]/4 pts)
	[need more detail]
o	Miscellaneous ([1]/3 pts)
	[paper not finish yet]
Estimated overall mark:
[57] out of [112].
Any other comments:
Although the project is not complete yet, but the part you have done is good and meets nearly all criteria in the rubric.  Additionally, ensuring that spelling and grammar are accurate throughout the paper is crucial for maintaining credibility and professionalism.

**Comment by leoyliu** [comment]
Thank you for the detailed peer review and thoughtful suggestions, Lorina. I've noted your feedback, including the need to finish the paper, explain relationships between variables, address model justification, and integrate additional visualizations. I’ll also work on improving in-text citations, addressing limitations, and proofreading for typos and grammatical errors. Your comments are incredibly helpful, and I’ll be incorporating these improvements. Closing this issue as I move forward with the revisions.
